### ISSUE TITLE
No module named 'pyannote.audio.features'

### ISSUE THREAD

**Issue by MedAmine-SUDO** [muskang48/Speaker-Diarization#2]
Hi, I was trying to run the diarization notebook on colab. I imported the model file and the audio file I want to test on but it gives me no module found error.

This is the complete error msg:

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-17-c3944f7fc67a> in <module>()
      1 #Give the path of audio file for Speaker Diarization (It should be Mono type.)
----> 2 segmented, n_clusters, hyp_df, result_hypo = diarization('./to_process.wav')
      3 print(n_clusters)
      4 print(hyp_df)
      5 result_hypo

<ipython-input-16-6e75bae0c3c0> in diarization(audiofile)
      8     splt = spliting(segmented,gp)
      9     resegmented = final_reseg(splt)
---> 10     embeddings = embeddings_(audiofile,resegmented,2)
     11     speak_id , n_speakers = clustering(embeddings)
     12     label_list = []

<ipython-input-13-6eebce9ac3e9> in embeddings_(audio_path, resegmented, range)
      5 import pyannote.core
      6 def embeddings_(audio_path,resegmented,range):
----> 7   model_emb = torch.hub.load('pyannote/pyannote-audio', 'emb')
      8 
      9   embedding = model_emb({'audio': audio_path})

/usr/local/lib/python3.7/dist-packages/torch/hub.py in load(repo_or_dir, model, *args, **kwargs)
    337         repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
    338 
--> 339     model = _load_local(repo_or_dir, model, *args, **kwargs)
    340     return model
    341 

/usr/local/lib/python3.7/dist-packages/torch/hub.py in _load_local(hubconf_dir, model, *args, **kwargs)
    363 
    364     hubconf_path = os.path.join(hubconf_dir, MODULE_HUBCONF)
--> 365     hub_module = import_module(MODULE_HUBCONF, hubconf_path)
    366 
    367     entry = _load_entry_from_hubconf(hub_module, model)

/usr/local/lib/python3.7/dist-packages/torch/hub.py in import_module(name, path)
     72     module = importlib.util.module_from_spec(spec)
     73     assert isinstance(spec.loader, Loader)
---> 74     spec.loader.exec_module(module)
     75     return module
     76 

/usr/lib/python3.7/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/root/.cache/torch/hub/pyannote_pyannote-audio_master/hubconf.py in <module>()
     35 import torch
     36 import yaml
---> 37 from pyannote.audio.features import Pretrained as _Pretrained
     38 from pyannote.pipeline import Pipeline as _Pipeline
     39 

ModuleNotFoundError: No module named 'pyannote.audio.features'

**Comment by muskang48** [comment]
**Installation:** !pip install pyannote.audio==1.1.1
